server:
  port: ${SERVER_PORT:8080}

spring:
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: ${POSTGRES_URL:no}
    username: ${POSTGRES_USERNAME:root}
    password: ${POSTGRES_PASSWORD:yes}
    driverClassName: org.postgresql.Driver